In [1]:
import os
path = "data"

In [2]:
categories = os.listdir(path)
category_codes = [i for i in range(len(categories))]
category_map = dict(zip(categories, category_codes))

print(categories)
print(category_codes)
print(category_map)

['without_mask', 'with_mask']
[0, 1]
{'without_mask': 0, 'with_mask': 1}


In [3]:
import cv2
feature = []
label = []

In [4]:
import numpy as np
image_size = 100
for category in categories:
    folder_path = os.path.join(path, category)
    images = os.listdir(folder_path)

    for image in images:
        image_path = os.path.join(folder_path, image)
        gray_image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        resized_image = cv2.resize(gray_image, (image_size, image_size))
        
        feature.append(resized_image)
        label.append(category_map[category])
print(feature[0].shape)
print(feature[0])

(100, 100)
[[ 9  9 10 ... 21 27 27]
 [ 8  8  7 ...  8 13 15]
 [12 10 10 ...  4  4  4]
 ...
 [66 67 58 ...  1  0  0]
 [66 64 53 ...  2  0  0]
 [60 56 49 ...  2  0  0]]


In [5]:
feature = np.array(feature) / 255
print(feature.shape)

(1376, 100, 100)


In [6]:
feature = np.reshape(feature, (feature.shape[0], image_size, image_size, 1))
print(feature.shape)

(1376, 100, 100, 1)


In [7]:
np.save('data', feature)
np.save('label', label)